import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import SurveyTool from "react-survey-tool";
import "react-survey-tool/css/SurveyTool.css";

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <SurveyTool
          surveyLink={`https://ms-survey-tool.vercel.app/survey/619ca919258963eb9e01c3e7?token=${props.surveyToken}`}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  return {
    props: { surveyToken: process.env.SURVEY_TOKEN }, // will be passed to the page component as props
  };
}
